name: Release
on:
  push:
    branch: 
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - run: apk add nodejs npm
      - run: npx appdmg ./create-dmg.json ./build/macos/Build/Products/Release/Toolboard.dmg

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/*.dmg"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}

      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DMG
          path: build/macos/Build/Products/Release/Toolboard.dmg
