name: Release
on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: arm64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - run: apk add nodejs npm
      - run: npx appdmg ./create-dmg.json ./build/macos/Build/Products/Release/Toolboard.dmg

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/macos/Build/Products/Release/*.dmg'
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}

      - name: Save build to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DMG
          path: build/macos/Build/Products/Release/Toolboard.dmg
